### ISSUE TITLE
Fixed site title

### ISSUE THREAD

**Issue by dashtinejad** [exirresearch/MAPFAN#10]
Fixed site title

- [x] Especially check the homepage

![image](https://cloud.githubusercontent.com/assets/8079021/23888012/ca3f1b22-089a-11e7-8d34-fb48df42e24a.png)

**Comment by mahdiafzal** [comment]
site title added in _Layout:
<title>پژوهشگاه نیرو | سامانه مدیریت داده های پژوهش و فناوری</title>
