### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by dashtinejad** [exirresearch/MAPFAN#11]
Create favicon based on this image, with https://realfavicongenerator.net/

- [x] Create favicon
- [x] Include it on project (via **Visual Studio 2015**)
- [x] Check the output.

![image](https://cloud.githubusercontent.com/assets/8079021/23888030/e620a54a-089a-11e7-9859-297e9e32d5de.png)

**Comment by mahdiafzal** [comment]
favicon added.
