### ISSUE TITLE
Text alignment of title in internal page

### ISSUE THREAD

**Issue by dashtinejad** [exirresearch/MAPFAN#12]
- [ ] Inside internal page, make alignment to center.
- [ ] Also there is a padding on the right, remove it.

![image](https://cloud.githubusercontent.com/assets/8079021/23888120/5792822a-089b-11e7-9956-595f5a00a1a5.png)

![image](https://cloud.githubusercontent.com/assets/8079021/23888125/62a41b9c-089b-11e7-88e1-91dd2cfee612.png)

**Comment by mahdiafzal** [comment]
Done
