### ISSUE TITLE
Internal Page Layout : height

### ISSUE THREAD

**Issue by dashtinejad** [exirresearch/MAPFAN#15]
The height of layout should be the height of window. The city background should always be visible.

![image](https://cloud.githubusercontent.com/assets/8079021/23888836/37d73c6a-089f-11e7-9d0b-33843a0caad6.png)

**Comment by mahdiafzal** [comment]
fixed height added in:
.right-box-list,
.middle-box-list,
.left-box-tab-pane-content

**Comment by mahdiafzal** [comment]
fixed height in .main-section
