### ISSUE TITLE
Add an image from homepage to the box

### ISSUE THREAD

**Issue by dashtinejad** [exirresearch/MAPFAN#7]
Add an image from homepage to the box.

![image](https://cloud.githubusercontent.com/assets/8079021/23887550/e1e817fe-0897-11e7-9849-d7ef92727f08.png)

![image](https://cloud.githubusercontent.com/assets/8079021/23887540/d145020e-0897-11e7-923c-811db85ef2cb.png)

**Comment by mahdiafzal** [comment]
Done

**Comment by mahdiafzal** [comment]
Done
