### ISSUE TITLE
Gray box and footer city background

### ISSUE THREAD

**Issue by dashtinejad** [exirresearch/MAPFAN#8]
The gray box color should go below the city background

![image](https://cloud.githubusercontent.com/assets/8079021/23887625/53a6077a-0898-11e7-8107-a5f7cb4446ae.png)

![image](https://cloud.githubusercontent.com/assets/8079021/23887633/60036dbe-0898-11e7-8013-33190129b37f.png)

**Comment by mahdiafzal** [comment]
Done
